
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xrelu_top.h"

/*
* The configuration table for devices
*/

XRelu_top_Config XRelu_top_ConfigTable[XPAR_XRELU_TOP_NUM_INSTANCES] =
{
	{
		XPAR_RELU_TOP_0_DEVICE_ID,
		XPAR_RELU_TOP_0_S_AXI_CONTROL_BASEADDR
	}
};


