# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/dianhsu/Desktop/Using_IP_with_Zynq/mylab/relu_vivado/relu_vivado.srcs/sources_1/bd/relu_bd/ip/relu_bd_relu_top_0_0/relu_bd_relu_top_0_0.xci
# IP: The module: 'relu_bd_relu_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dianhsu/Desktop/Using_IP_with_Zynq/mylab/relu_vivado/relu_vivado.gen/sources_1/bd/relu_bd/ip/relu_bd_relu_top_0_0/constraints/relu_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'relu_bd_relu_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/dianhsu/Desktop/Using_IP_with_Zynq/mylab/relu_vivado/relu_vivado.srcs/sources_1/bd/relu_bd/ip/relu_bd_relu_top_0_0/relu_bd_relu_top_0_0.xci
# IP: The module: 'relu_bd_relu_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dianhsu/Desktop/Using_IP_with_Zynq/mylab/relu_vivado/relu_vivado.gen/sources_1/bd/relu_bd/ip/relu_bd_relu_top_0_0/constraints/relu_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'relu_bd_relu_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
